wandb_version: 1

dataset:
  desc: null
  value:
    hr_train_img_folder: H:/dataset/DIV2K/DIV2K_train_HR_sub
    lr_train_img_folder: H:/dataset/DIV2K/DIV2K_train_LR_unknown_X4_sub
    hr_val_img_folder: H:/dataset/DIV2K/DIV2K_valid_HR_sub
    lr_val_img_folder: H:/dataset/DIV2K/DIV2K_valid_LR_unknown_X4_sub
    save_path: save
hyperparameters:
  desc: null
  value:
    lr: 0.01
    batch_size: 32
    num_workers: 4
    epoch: 100
    lr_decay_schedule:
    - 1
    - 8
    - 16
    - 32
    loss_name: MSE
    add_perceptual_loss: false
    add_edge_loss: false
    coefficient_perceptual_loss: 0.0001
    coefficient_edge_loss: 0.1
    optimizer_name: Adam
    model_num: 0
model0:
  desc: null
  value:
    num_blocks: 8
    image_size: 128
model1:
  desc: null
  value:
    image_size: 128
    in_channels: 3
    out_channels_after_conv1: 16
    out_channels_after_conv2: 64
    patch_sizes:
    - 4
    - 8
    - 12
    num_blocks:
    - 4
    - 2
    - 1
    upscale_factor: 4
model2:
  desc: null
  value:
    image_size: 128
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700313971.022355
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.10.9
      5: 0.15.12
      8:
      - 3
      - 5
      13: windows-amd64
