wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1680357875.288936
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.9.13
      5: 0.14.0
      8:
      - 3
      - 5
architecture:
  desc: null
  value: "SRG2(\n  (layers): Sequential(\n    (conv_1): Conv2d(3, 16, kernel_size=(13,\
    \ 13), stride=(1, 1), padding=(6, 6))\n    (leaky_relu1): LeakyReLU(negative_slope=0.01,\
    \ inplace=True)\n    (conv_2): Conv2d(16, 32, kernel_size=(9, 9), stride=(1, 1),\
    \ padding=(4, 4))\n    (leaky_relu2): LeakyReLU(negative_slope=0.01, inplace=True)\n\
    \    (conv_3): Conv2d(32, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))\n\
    \    (leaky_relu3): LeakyReLU(negative_slope=0.01, inplace=True)\n    (conv_4):\
    \ Conv2d(16, 12, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))\n    (leaky_relu4):\
    \ LeakyReLU(negative_slope=0.01, inplace=True)\n    (conv_transposed1): ConvTranspose2d(12,\
    \ 8, kernel_size=(6, 6), stride=(2, 2), padding=(2, 2), bias=False)\n    (leaky_relu5):\
    \ LeakyReLU(negative_slope=0.01, inplace=True)\n    (conv_transposed2): ConvTranspose2d(8,\
    \ 3, kernel_size=(6, 6), stride=(2, 2), padding=(2, 2), bias=False)\n  )\n)"
criterion:
  desc: null
  value: MSELoss
dataset:
  desc: null
  value: another anime face dataset
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.02
optimization:
  desc: null
  value: Adam
