T: 500
beta_min: 0.0001
beta_max: 0.02

batch_size: 16
num_workers: 4
lr: 0.0001
image_size: 512
epoch: 10

image_folder: H:/dataset/animal faces/train/cat # 训练集路径
save_path: saved_model #模型的保存路径

upscale_factor: 4