T: 1000
beta_min: 0.0001
beta_max: 0.02

batch_size: 64
num_workers: 4
lr: 0.00001
image_size: 64
epoch: 50

image_folder: H:/dataset/anime face # 训练集路径
save_path: saved_model #模型的保存路径

upscale_factor: 4