#test_lr_dir: E:\datasets\DIV2K\DIV2K_valid_LR_unknown_X4_sub
#test_gt_dir: E:\datasets\DIV2K\DIV2K_valid_HR_sub
test_lr_dir: E:\datasets\Set14_SR\Set14\image_SRF_4\LR_sub
test_gt_dir: E:\datasets\Set14_SR\Set14\image_SRF_4\HR_sub
#test_lr_dir: E:\datasets\Set5_SR\Set5\image_SRF_4\LR_sub
#test_gt_dir: E:\datasets\Set5_SR\Set5\image_SRF_4\HR_sub
#test_lr_dir: E:\datasets\Urban100_SR\image_SRF_4\LR_sub
#test_gt_dir: E:\datasets\Urban100_SR\image_SRF_4\HR_sub
model_parameters_path: save\checkpoint-6k.pth



log_path: log # 测试结果输出路径