wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1680357351.526658
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.9.13
      5: 0.14.0
      8:
      - 3
      - 5
architecture:
  desc: null
  value: CNN+transposed CNN
criterion:
  desc: null
  value: MSELoss
dataset:
  desc: null
  value: another anime face dataset
epochs:
  desc: null
  value: 20
learning_rate:
  desc: null
  value: 0.02
optimization:
  desc: null
  value: Adam
